// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDashboardPreferencesByUserID = `-- name: DeleteDashboardPreferencesByUserID :exec
DELETE FROM dashboard_preferences WHERE user_id = $1
`

func (q *Queries) DeleteDashboardPreferencesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteDashboardPreferencesByUserID, userID)
	return err
}

const getDashboardLayout = `-- name: GetDashboardLayout :one
SELECT user_id, stats_columns, charts_columns, excluded_host_group_ids, updated_at
FROM dashboard_layout
WHERE user_id = $1
`

func (q *Queries) GetDashboardLayout(ctx context.Context, userID string) (DashboardLayout, error) {
	row := q.db.QueryRow(ctx, getDashboardLayout, userID)
	var i DashboardLayout
	err := row.Scan(
		&i.UserID,
		&i.StatsColumns,
		&i.ChartsColumns,
		&i.ExcludedHostGroupIds,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDashboardPreference = `-- name: InsertDashboardPreference :exec
INSERT INTO dashboard_preferences (id, user_id, card_id, enabled, "order", col_span, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDashboardPreferenceParams struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	CardID    string           `json:"card_id"`
	Enabled   bool             `json:"enabled"`
	Order     int32            `json:"order"`
	ColSpan   int32            `json:"col_span"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) InsertDashboardPreference(ctx context.Context, arg InsertDashboardPreferenceParams) error {
	_, err := q.db.Exec(ctx, insertDashboardPreference,
		arg.ID,
		arg.UserID,
		arg.CardID,
		arg.Enabled,
		arg.Order,
		arg.ColSpan,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDashboardPreferencesByUserID = `-- name: ListDashboardPreferencesByUserID :many
SELECT id, user_id, card_id, enabled, "order", col_span, created_at, updated_at
FROM dashboard_preferences
WHERE user_id = $1
ORDER BY "order" ASC
`

func (q *Queries) ListDashboardPreferencesByUserID(ctx context.Context, userID string) ([]DashboardPreference, error) {
	rows, err := q.db.Query(ctx, listDashboardPreferencesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardPreference
	for rows.Next() {
		var i DashboardPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Enabled,
			&i.Order,
			&i.ColSpan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDashboardLayout = `-- name: UpsertDashboardLayout :exec
INSERT INTO dashboard_layout (user_id, stats_columns, charts_columns, excluded_host_group_ids, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    stats_columns = EXCLUDED.stats_columns,
    charts_columns = EXCLUDED.charts_columns,
    excluded_host_group_ids = EXCLUDED.excluded_host_group_ids,
    updated_at = EXCLUDED.updated_at
`

type UpsertDashboardLayoutParams struct {
	UserID               string           `json:"user_id"`
	StatsColumns         int32            `json:"stats_columns"`
	ChartsColumns        int32            `json:"charts_columns"`
	ExcludedHostGroupIds []string         `json:"excluded_host_group_ids"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertDashboardLayout(ctx context.Context, arg UpsertDashboardLayoutParams) error {
	_, err := q.db.Exec(ctx, upsertDashboardLayout,
		arg.UserID,
		arg.StatsColumns,
		arg.ChartsColumns,
		arg.ExcludedHostGroupIds,
		arg.UpdatedAt,
	)
	return err
}
