// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remote_access_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRemoteAccessSessions = `-- name: CountRemoteAccessSessions :one
SELECT COUNT(*)::int
FROM remote_access_sessions ras
JOIN users u ON u.id = ras.user_id
JOIN hosts h ON h.id = ras.host_id
WHERE ($1::text = '' OR ras.protocol = $1::text)
  AND ($2::text = '' OR ras.status = $2::text)
  AND ($3::text = '' OR ras.host_id = $3::text)
  AND ($4::text = '' OR ras.user_id = $4::text)
  AND (
      $5::text = ''
      OR u.username ILIKE '%' || $5::text || '%'
      OR h.friendly_name ILIKE '%' || $5::text || '%'
      OR COALESCE(h.hostname, '') ILIKE '%' || $5::text || '%'
      OR ras.connection_mode ILIKE '%' || $5::text || '%'
  )
`

type CountRemoteAccessSessionsParams struct {
	Protocol string `json:"protocol"`
	Status   string `json:"status"`
	HostID   string `json:"host_id"`
	UserID   string `json:"user_id"`
	Search   string `json:"search"`
}

func (q *Queries) CountRemoteAccessSessions(ctx context.Context, arg CountRemoteAccessSessionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRemoteAccessSessions,
		arg.Protocol,
		arg.Status,
		arg.HostID,
		arg.UserID,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRemoteAccessSession = `-- name: CreateRemoteAccessSession :one
INSERT INTO remote_access_sessions (
    id,
    user_id,
    host_id,
    protocol,
    connection_mode,
    status,
    browser_ip,
    user_agent,
    proxy_session_id,
    guacd_session_id,
    recording_status,
    recording_path,
    recording_name
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    'connecting',
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::text
)
RETURNING id, user_id, host_id, protocol, connection_mode, status, started_at, connected_at, ended_at, error_message, browser_ip, user_agent, proxy_session_id, guacd_session_id, recording_status, recording_path, recording_name, recording_size_bytes, created_at, updated_at
`

type CreateRemoteAccessSessionParams struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	HostID          string  `json:"host_id"`
	Protocol        string  `json:"protocol"`
	ConnectionMode  string  `json:"connection_mode"`
	BrowserIp       *string `json:"browser_ip"`
	UserAgent       *string `json:"user_agent"`
	ProxySessionID  *string `json:"proxy_session_id"`
	GuacdSessionID  *string `json:"guacd_session_id"`
	RecordingStatus string  `json:"recording_status"`
	RecordingPath   *string `json:"recording_path"`
	RecordingName   *string `json:"recording_name"`
}

func (q *Queries) CreateRemoteAccessSession(ctx context.Context, arg CreateRemoteAccessSessionParams) (RemoteAccessSession, error) {
	row := q.db.QueryRow(ctx, createRemoteAccessSession,
		arg.ID,
		arg.UserID,
		arg.HostID,
		arg.Protocol,
		arg.ConnectionMode,
		arg.BrowserIp,
		arg.UserAgent,
		arg.ProxySessionID,
		arg.GuacdSessionID,
		arg.RecordingStatus,
		arg.RecordingPath,
		arg.RecordingName,
	)
	var i RemoteAccessSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HostID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.Status,
		&i.StartedAt,
		&i.ConnectedAt,
		&i.EndedAt,
		&i.ErrorMessage,
		&i.BrowserIp,
		&i.UserAgent,
		&i.ProxySessionID,
		&i.GuacdSessionID,
		&i.RecordingStatus,
		&i.RecordingPath,
		&i.RecordingName,
		&i.RecordingSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemoteAccessSession = `-- name: GetRemoteAccessSession :one
SELECT
    ras.id, ras.user_id, ras.host_id, ras.protocol, ras.connection_mode, ras.status, ras.started_at, ras.connected_at, ras.ended_at, ras.error_message, ras.browser_ip, ras.user_agent, ras.proxy_session_id, ras.guacd_session_id, ras.recording_status, ras.recording_path, ras.recording_name, ras.recording_size_bytes, ras.created_at, ras.updated_at,
    u.username AS user_username,
    h.friendly_name AS host_friendly_name,
    h.hostname AS host_hostname
FROM remote_access_sessions ras
JOIN users u ON u.id = ras.user_id
JOIN hosts h ON h.id = ras.host_id
WHERE ras.id = $1::text
`

type GetRemoteAccessSessionRow struct {
	ID                 string           `json:"id"`
	UserID             string           `json:"user_id"`
	HostID             string           `json:"host_id"`
	Protocol           string           `json:"protocol"`
	ConnectionMode     string           `json:"connection_mode"`
	Status             string           `json:"status"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	ConnectedAt        pgtype.Timestamp `json:"connected_at"`
	EndedAt            pgtype.Timestamp `json:"ended_at"`
	ErrorMessage       *string          `json:"error_message"`
	BrowserIp          *string          `json:"browser_ip"`
	UserAgent          *string          `json:"user_agent"`
	ProxySessionID     *string          `json:"proxy_session_id"`
	GuacdSessionID     *string          `json:"guacd_session_id"`
	RecordingStatus    string           `json:"recording_status"`
	RecordingPath      *string          `json:"recording_path"`
	RecordingName      *string          `json:"recording_name"`
	RecordingSizeBytes *int64           `json:"recording_size_bytes"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	UserUsername       string           `json:"user_username"`
	HostFriendlyName   string           `json:"host_friendly_name"`
	HostHostname       *string          `json:"host_hostname"`
}

func (q *Queries) GetRemoteAccessSession(ctx context.Context, id string) (GetRemoteAccessSessionRow, error) {
	row := q.db.QueryRow(ctx, getRemoteAccessSession, id)
	var i GetRemoteAccessSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HostID,
		&i.Protocol,
		&i.ConnectionMode,
		&i.Status,
		&i.StartedAt,
		&i.ConnectedAt,
		&i.EndedAt,
		&i.ErrorMessage,
		&i.BrowserIp,
		&i.UserAgent,
		&i.ProxySessionID,
		&i.GuacdSessionID,
		&i.RecordingStatus,
		&i.RecordingPath,
		&i.RecordingName,
		&i.RecordingSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUsername,
		&i.HostFriendlyName,
		&i.HostHostname,
	)
	return i, err
}

const listRemoteAccessSessions = `-- name: ListRemoteAccessSessions :many
SELECT
    ras.id, ras.user_id, ras.host_id, ras.protocol, ras.connection_mode, ras.status, ras.started_at, ras.connected_at, ras.ended_at, ras.error_message, ras.browser_ip, ras.user_agent, ras.proxy_session_id, ras.guacd_session_id, ras.recording_status, ras.recording_path, ras.recording_name, ras.recording_size_bytes, ras.created_at, ras.updated_at,
    u.username AS user_username,
    h.friendly_name AS host_friendly_name,
    h.hostname AS host_hostname
FROM remote_access_sessions ras
JOIN users u ON u.id = ras.user_id
JOIN hosts h ON h.id = ras.host_id
WHERE ($1::text = '' OR ras.protocol = $1::text)
  AND ($2::text = '' OR ras.status = $2::text)
  AND ($3::text = '' OR ras.host_id = $3::text)
  AND ($4::text = '' OR ras.user_id = $4::text)
  AND (
      $5::text = ''
      OR u.username ILIKE '%' || $5::text || '%'
      OR h.friendly_name ILIKE '%' || $5::text || '%'
      OR COALESCE(h.hostname, '') ILIKE '%' || $5::text || '%'
      OR ras.connection_mode ILIKE '%' || $5::text || '%'
  )
ORDER BY ras.started_at DESC
LIMIT $7::int
OFFSET $6::int
`

type ListRemoteAccessSessionsParams struct {
	Protocol  string `json:"protocol"`
	Status    string `json:"status"`
	HostID    string `json:"host_id"`
	UserID    string `json:"user_id"`
	Search    string `json:"search"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

type ListRemoteAccessSessionsRow struct {
	ID                 string           `json:"id"`
	UserID             string           `json:"user_id"`
	HostID             string           `json:"host_id"`
	Protocol           string           `json:"protocol"`
	ConnectionMode     string           `json:"connection_mode"`
	Status             string           `json:"status"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	ConnectedAt        pgtype.Timestamp `json:"connected_at"`
	EndedAt            pgtype.Timestamp `json:"ended_at"`
	ErrorMessage       *string          `json:"error_message"`
	BrowserIp          *string          `json:"browser_ip"`
	UserAgent          *string          `json:"user_agent"`
	ProxySessionID     *string          `json:"proxy_session_id"`
	GuacdSessionID     *string          `json:"guacd_session_id"`
	RecordingStatus    string           `json:"recording_status"`
	RecordingPath      *string          `json:"recording_path"`
	RecordingName      *string          `json:"recording_name"`
	RecordingSizeBytes *int64           `json:"recording_size_bytes"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	UserUsername       string           `json:"user_username"`
	HostFriendlyName   string           `json:"host_friendly_name"`
	HostHostname       *string          `json:"host_hostname"`
}

func (q *Queries) ListRemoteAccessSessions(ctx context.Context, arg ListRemoteAccessSessionsParams) ([]ListRemoteAccessSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRemoteAccessSessions,
		arg.Protocol,
		arg.Status,
		arg.HostID,
		arg.UserID,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRemoteAccessSessionsRow
	for rows.Next() {
		var i ListRemoteAccessSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HostID,
			&i.Protocol,
			&i.ConnectionMode,
			&i.Status,
			&i.StartedAt,
			&i.ConnectedAt,
			&i.EndedAt,
			&i.ErrorMessage,
			&i.BrowserIp,
			&i.UserAgent,
			&i.ProxySessionID,
			&i.GuacdSessionID,
			&i.RecordingStatus,
			&i.RecordingPath,
			&i.RecordingName,
			&i.RecordingSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserUsername,
			&i.HostFriendlyName,
			&i.HostHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRemoteAccessSessionConnected = `-- name: MarkRemoteAccessSessionConnected :exec
UPDATE remote_access_sessions
SET
    status = 'connected',
    connected_at = COALESCE(connected_at, CURRENT_TIMESTAMP),
    error_message = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1::text
  AND status = 'connecting'
`

func (q *Queries) MarkRemoteAccessSessionConnected(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRemoteAccessSessionConnected, id)
	return err
}

const markRemoteAccessSessionEnded = `-- name: MarkRemoteAccessSessionEnded :exec
UPDATE remote_access_sessions
SET
    status = $1::text,
    ended_at = COALESCE(ended_at, CURRENT_TIMESTAMP),
    error_message = $2::text,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3::text
  AND ended_at IS NULL
`

type MarkRemoteAccessSessionEndedParams struct {
	Status       string  `json:"status"`
	ErrorMessage *string `json:"error_message"`
	ID           string  `json:"id"`
}

func (q *Queries) MarkRemoteAccessSessionEnded(ctx context.Context, arg MarkRemoteAccessSessionEndedParams) error {
	_, err := q.db.Exec(ctx, markRemoteAccessSessionEnded, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const setRemoteAccessSessionGuacdID = `-- name: SetRemoteAccessSessionGuacdID :exec
UPDATE remote_access_sessions
SET
    guacd_session_id = $1::text,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::text
`

type SetRemoteAccessSessionGuacdIDParams struct {
	GuacdSessionID string `json:"guacd_session_id"`
	ID             string `json:"id"`
}

func (q *Queries) SetRemoteAccessSessionGuacdID(ctx context.Context, arg SetRemoteAccessSessionGuacdIDParams) error {
	_, err := q.db.Exec(ctx, setRemoteAccessSessionGuacdID, arg.GuacdSessionID, arg.ID)
	return err
}

const setRemoteAccessSessionProxyID = `-- name: SetRemoteAccessSessionProxyID :exec
UPDATE remote_access_sessions
SET
    proxy_session_id = $1::text,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2::text
`

type SetRemoteAccessSessionProxyIDParams struct {
	ProxySessionID string `json:"proxy_session_id"`
	ID             string `json:"id"`
}

func (q *Queries) SetRemoteAccessSessionProxyID(ctx context.Context, arg SetRemoteAccessSessionProxyIDParams) error {
	_, err := q.db.Exec(ctx, setRemoteAccessSessionProxyID, arg.ProxySessionID, arg.ID)
	return err
}

const setRemoteAccessSessionRecording = `-- name: SetRemoteAccessSessionRecording :exec
UPDATE remote_access_sessions
SET
    recording_status = $1::text,
    recording_path = $2::text,
    recording_name = $3::text,
    recording_size_bytes = $4::bigint,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5::text
`

type SetRemoteAccessSessionRecordingParams struct {
	RecordingStatus    string  `json:"recording_status"`
	RecordingPath      *string `json:"recording_path"`
	RecordingName      *string `json:"recording_name"`
	RecordingSizeBytes *int64  `json:"recording_size_bytes"`
	ID                 string  `json:"id"`
}

func (q *Queries) SetRemoteAccessSessionRecording(ctx context.Context, arg SetRemoteAccessSessionRecordingParams) error {
	_, err := q.db.Exec(ctx, setRemoteAccessSessionRecording,
		arg.RecordingStatus,
		arg.RecordingPath,
		arg.RecordingName,
		arg.RecordingSizeBytes,
		arg.ID,
	)
	return err
}
